import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'ru',
  title: 'DevOps',
  description: 'Личные конспекты и практика по DevOps — Git, Docker, CI/CD, Kubernetes',
  base: '/DevOps-Course/',

  markdown: {
    lineNumbers: true,
  },

  themeConfig: {
    nav: [
      { text: 'Главная', link: '/' },
      { text: 'Git', link: '/git/' },
      { text: 'Linux', link: '/linux/' },
      { text: 'Сети', link: '/network/' },
      { text: 'Docker', link: '/docker/' },
      { text: 'CI/CD', link: '/cicd/' },
      { text: 'Ansible', link: '/ansible/' },
      { text: 'Kubernetes', link: '/kubernetes/' },
      { text: 'Базы данных', link: '/databases/' },
      { text: 'Мониторинг', link: '/monitoring/' },
      { text: 'Логирование', link: '/logging/' },
      { text: 'ArgoCD', link: '/argocd/' },
      { text: 'Очереди', link: '/queues/' },
      { text: 'Облака', link: '/cloud/' },
      { text: 'Terraform', link: '/terraform/' },
      { text: 'Vault', link: '/vault/' },
    ],

    sidebar: {
      '/vault/': [
        {
          text: 'Vault',
          items: [
            { text: 'Обзор темы', link: '/vault/' },
            { text: '01. Проблема секретов', link: '/vault/01-secrets-problem' },
            { text: '02. Что такое Vault и как он устроен', link: '/vault/02-vault-intro' },
            { text: '03. KV secret engine', link: '/vault/03-kv-engine' },
            { text: '04. Auth methods и политики', link: '/vault/04-auth-methods' },
            { text: '05. Интеграции и динамические секреты', link: '/vault/05-vault-integrations' },
            { text: '06. Практика: 4 лабы', link: '/vault/06-practice-labs' },
            { text: '07. Вопросы с собеседований', link: '/vault/07-interview' },
          ],
        },
      ],
      '/cloud/': [
        {
          text: 'Облака',
          items: [
            { text: 'Обзор темы', link: '/cloud/' },
            { text: '01. Модели облаков: IaaS, PaaS, SaaS', link: '/cloud/01-cloud-models' },
            { text: '02. ВМ и подключение по SSH', link: '/cloud/02-compute-ssh' },
            { text: '03. Сеть в облаке: VPC', link: '/cloud/03-network-vpc' },
            { text: '04. S3 и объектное хранилище', link: '/cloud/04-s3-storage' },
            { text: '05. Managed-сервисы', link: '/cloud/05-managed-services' },
            { text: '06. Практика: 5 лаб', link: '/cloud/06-practice-labs' },
            { text: '07. Вопросы с собеседований', link: '/cloud/07-interview' },
            { text: '08. AWS глубже', link: '/cloud/08-aws-deep' },
            { text: '09. Yandex Cloud глубже', link: '/cloud/09-yandex-cloud' },
            { text: '10. Казахстанские облака', link: '/cloud/10-kz-clouds' },
          ],
        },
      ],
      '/terraform/': [
        {
          text: 'Terraform',
          items: [
            { text: 'Обзор темы', link: '/terraform/' },
            { text: '01. Infrastructure as Code', link: '/terraform/01-iac-intro' },
            { text: '02. Terraform: основы', link: '/terraform/02-terraform-basics' },
            { text: '03. State и backend', link: '/terraform/03-state-backend' },
            { text: '04. Переменные и outputs', link: '/terraform/04-variables-outputs' },
            { text: '05. Модули', link: '/terraform/05-modules' },
            { text: '06. Workflow и CI/CD', link: '/terraform/06-workflow-cicd' },
            { text: '07. Практика: лабы', link: '/terraform/07-practice-labs' },
            { text: '08. Вопросы с собеседований', link: '/terraform/08-interview' },
            { text: '09. Тестирование', link: '/terraform/09-testing' },
          ],
        },
      ],
      '/queues/': [
        {
          text: 'Очереди',
          items: [
            { text: 'Обзор темы', link: '/queues/' },
            { text: '01. Основы очередей сообщений', link: '/queues/01-queues-concepts' },
            { text: '02. Kafka: концепции', link: '/queues/02-kafka-basics' },
            { text: '03. Kafka: эксплуатация', link: '/queues/03-kafka-ops' },
            { text: '04. RabbitMQ', link: '/queues/04-rabbitmq' },
            { text: '05. Практика: 4 лабы', link: '/queues/05-practice-labs' },
            { text: '06. Вопросы с собеседований', link: '/queues/06-interview' },
          ],
        },
      ],
      '/argocd/': [
        {
          text: 'ArgoCD',
          items: [
            { text: 'Обзор темы', link: '/argocd/' },
            { text: '01. Принципы GitOps', link: '/argocd/01-gitops-concepts' },
            { text: '02. Установка и устройство ArgoCD', link: '/argocd/02-argocd-install' },
            { text: '03. Application: синхронизация и здоровье', link: '/argocd/03-application' },
            { text: '04. App of Apps и ApplicationSet', link: '/argocd/04-app-of-apps' },
            { text: '05. Helm, Kustomize и секреты в GitOps', link: '/argocd/05-helm-kustomize' },
            { text: '06. Практика: 4 лабы', link: '/argocd/06-practice-labs' },
            { text: '07. Вопросы с собеседований', link: '/argocd/07-interview' },
          ],
        },
      ],
      '/logging/': [
        {
          text: 'Логирование',
          items: [
            { text: 'Обзор темы', link: '/logging/' },
            { text: '01. Основы логирования', link: '/logging/01-logging-concepts' },
            { text: '02. ELK: Elasticsearch, Logstash, Kibana', link: '/logging/02-elk-stack' },
            { text: '03. Loki + Grafana', link: '/logging/03-loki-grafana' },
            { text: '04. Сборщики логов', link: '/logging/04-collectors' },
            { text: '05. Источники логов', link: '/logging/05-log-sources' },
            { text: '06. Практика: 5 лаб', link: '/logging/06-practice-labs' },
            { text: '07. Вопросы с собеседований', link: '/logging/07-interview' },
            { text: '08. OpenTelemetry и Vector', link: '/logging/08-otel-logs-vector' },
          ],
        },
      ],
      '/monitoring/': [
        {
          text: 'Мониторинг',
          items: [
            { text: 'Обзор темы', link: '/monitoring/' },
            { text: '01. Основы мониторинга', link: '/monitoring/01-monitoring-concepts' },
            { text: '02. Prometheus: архитектура и сбор', link: '/monitoring/02-prometheus-basics' },
            { text: '03. Типы метрик и PromQL', link: '/monitoring/03-promql' },
            { text: "04. Exporter'ы", link: '/monitoring/04-exporters' },
            { text: '05. Алерты и Alertmanager', link: '/monitoring/05-alertmanager' },
            { text: '06. Grafana', link: '/monitoring/06-grafana' },
            { text: '07. Что мониторить: 4 сигнала, USE, RED, SLO', link: '/monitoring/07-what-to-monitor' },
            { text: '08. Практика: 6 лаб', link: '/monitoring/08-practice-labs' },
            { text: '09. Вопросы с собеседований', link: '/monitoring/09-interview' },
            { text: '10. Zabbix', link: '/monitoring/10-zabbix' },
            { text: '11. Долгое хранение и Operator', link: '/monitoring/11-long-term-and-operator' },
          ],
        },
      ],
      '/databases/': [
        {
          text: 'Базы данных',
          items: [
            { text: 'Обзор темы', link: '/databases/' },
            { text: '01. База данных глазами DevOps', link: '/databases/01-db-for-devops' },
            { text: '02. PostgreSQL: установка и устройство', link: '/databases/02-pg-install' },
            { text: '03. Доступ: pg_hba.conf, роли и права', link: '/databases/03-pg-hba-access' },
            { text: '04. postgresql.conf — основные параметры', link: '/databases/04-postgresql-conf' },
            { text: '05. Бэкап и восстановление', link: '/databases/05-backup-restore' },
            { text: '06. Репликация PostgreSQL', link: '/databases/06-replication' },
            { text: '07. Мониторинг баз данных', link: '/databases/07-db-monitoring' },
            { text: '08. Базовый SQL для DevOps', link: '/databases/08-sql-basics' },
            { text: '09. Redis, MongoDB, ClickHouse', link: '/databases/09-redis-mongo-clickhouse' },
            { text: '10. Практика: 7 лаб', link: '/databases/10-practice-labs' },
            { text: '11. Вопросы с собеседований', link: '/databases/11-interview' },
            { text: '12. MySQL и MariaDB', link: '/databases/12-mysql' },
            { text: '13. Миграции схемы', link: '/databases/13-schema-migrations' },
          ],
        },
      ],
      '/kubernetes/': [
        {
          text: 'Kubernetes',
          items: [
            { text: 'Обзор темы', link: '/kubernetes/' },
            { text: '01. Зачем нужен Kubernetes', link: '/kubernetes/01-k8s-intro' },
            { text: '02. Архитектура кластера', link: '/kubernetes/02-architecture' },
            { text: '03. kubectl и манифесты', link: '/kubernetes/03-kubectl-manifests' },
            { text: '04. Pod — минимальная единица', link: '/kubernetes/04-pod' },
            { text: '05. Deployment и ReplicaSet', link: '/kubernetes/05-deployment' },
            { text: '06. DaemonSet и StatefulSet', link: '/kubernetes/06-daemonset-statefulset' },
            { text: '07. Job и CronJob', link: '/kubernetes/07-job-cronjob' },
            { text: '08. ConfigMap и Secret', link: '/kubernetes/08-configmap-secret' },
            { text: '09. Проверки (probes) и ресурсы', link: '/kubernetes/09-probes-resources' },
            { text: '10. Сеть под капотом', link: '/kubernetes/10-network-internals' },
            { text: '11. Service', link: '/kubernetes/11-service' },
            { text: '12. Ingress и Ingress Controller', link: '/kubernetes/12-ingress' },
            { text: '13. NetworkPolicy', link: '/kubernetes/13-networkpolicy' },
            { text: '14. Хранилище: PV, PVC, StorageClass', link: '/kubernetes/14-storage' },
            { text: '15. Helm', link: '/kubernetes/15-helm' },
            { text: '16. Развёртывание кластера', link: '/kubernetes/16-cluster-deployment' },
            { text: '17. RBAC', link: '/kubernetes/17-rbac' },
            { text: '18. HPA и автоскейлинг', link: '/kubernetes/18-hpa-autoscaling' },
            { text: '19. Планирование подов', link: '/kubernetes/19-scheduling' },
            { text: '20. Траблшутинг кластера', link: '/kubernetes/20-troubleshooting' },
            { text: '21. Развилка: куда дальше', link: '/kubernetes/21-advanced-paths' },
            { text: '22. Практика: лабы из роадмапа', link: '/kubernetes/22-practice-labs' },
            { text: '23. Вопросы с собеседований', link: '/kubernetes/23-interview' },
            { text: '24. Жизненный цикл кластера', link: '/kubernetes/24-cluster-lifecycle' },
            { text: '25. Экосистема вокруг кластера', link: '/kubernetes/25-ecosystem' },
          ],
        },
      ],
      '/ansible/': [
        {
          text: 'Ansible',
          items: [
            { text: 'Обзор темы', link: '/ansible/' },
            { text: '01. Введение в Ansible', link: '/ansible/01-ansible-intro' },
            { text: '02. Установка и подключение', link: '/ansible/02-setup-connection' },
            { text: '03. Inventory', link: '/ansible/03-inventory' },
            { text: '04. Ad-hoc команды', link: '/ansible/04-ad-hoc' },
            { text: '05. Модули', link: '/ansible/05-modules' },
            { text: '06. Основы плейбуков', link: '/ansible/06-playbook-basics' },
            { text: '07. Переменные и facts', link: '/ansible/07-variables-facts' },
            { text: '08. Условия и циклы', link: '/ansible/08-conditions-loops' },
            { text: '09. Handlers и идемпотентность', link: '/ansible/09-handlers-idempotency' },
            { text: '10. Шаблоны и Jinja2', link: '/ansible/10-templates-jinja2' },
            { text: '11. Роли', link: '/ansible/11-roles' },
            { text: '12. Ansible Vault', link: '/ansible/12-vault' },
            { text: '13. Best practices, отладка, CI/CD', link: '/ansible/13-best-practices' },
            { text: '14. Практика: лабы из роадмапа', link: '/ansible/14-practice-labs' },
            { text: '15. Вопросы с собеседований', link: '/ansible/15-interview' },
          ],
        },
      ],
      '/cicd/': [
        {
          text: 'CI/CD',
          items: [
            { text: 'Обзор темы', link: '/cicd/' },
            { text: '01. CI, CD и CD — концепции', link: '/cicd/01-cicd-concepts' },
            { text: '02. Стратегии ветвления и версионирование', link: '/cicd/02-git-workflows' },
            { text: '03. Проектирование пайплайна', link: '/cicd/03-pipeline-design' },
            { text: '04. GitOps', link: '/cicd/04-gitops' },
            { text: '05. GitLab CI: pipeline, stage, job', link: '/cicd/05-gitlab-ci-basics' },
            { text: '06. GitLab CI: rules, variables, artifacts', link: '/cicd/06-gitlab-ci-core' },
            { text: '07. Docker в GitLab CI и Registry', link: '/cicd/07-gitlab-ci-docker' },
            { text: '08. GitLab CI: needs, extends, include, trigger', link: '/cicd/08-gitlab-ci-advanced' },
            { text: '09. GitLab Runner', link: '/cicd/09-gitlab-runner' },
            { text: '10. Jenkins: архитектура и основы', link: '/cicd/10-jenkins-basics' },
            { text: '11. Jenkinsfile и декларативный пайплайн', link: '/cicd/11-jenkins-pipeline' },
            { text: '12. Jenkins: Groovy, Shared Libraries', link: '/cicd/12-jenkins-advanced' },
            { text: '13. Качество и безопасность пайплайна', link: '/cicd/13-quality-security' },
            { text: '14. Практика: лабы из роадмапа', link: '/cicd/14-practice-labs' },
            { text: '15. Вопросы с собеседований', link: '/cicd/15-interview' },
            { text: '16. GitHub Actions', link: '/cicd/16-github-actions' },
          ],
        },
      ],
      '/docker/': [
        {
          text: 'Docker',
          items: [
            { text: 'Обзор темы', link: '/docker/' },
            { text: '01. Контейнеры и архитектура Docker', link: '/docker/01-containers-intro' },
            { text: '02. Образы: слои, overlay2, теги', link: '/docker/02-images-layers' },
            { text: '03. Dockerfile: директивы и контекст сборки', link: '/docker/03-dockerfile' },
            { text: '04. Кэш сборки, multi-stage и best practices', link: '/docker/04-build-cache-multistage' },
            { text: '05. Registry и тегирование', link: '/docker/05-registry-tags' },
            { text: '06. Жизненный цикл контейнера', link: '/docker/06-containers-lifecycle' },
            { text: '07. Данные: volumes, bind mounts, tmpfs', link: '/docker/07-volumes-storage' },
            { text: '08. Сеть в Docker', link: '/docker/08-network' },
            { text: '09. Docker Compose', link: '/docker/09-compose' },
            { text: '10. Безопасность контейнеров', link: '/docker/10-security-best-practices' },
            { text: '11. Troubleshooting и обслуживание', link: '/docker/11-troubleshooting' },
            { text: '12. Практика: лабы', link: '/docker/12-practice-labs' },
            { text: '13. Вопросы с собеседований', link: '/docker/13-interview' },
          ],
        },
      ],
      '/network/': [
        {
          text: 'Сети',
          items: [
            { text: 'Обзор темы', link: '/network/' },
            { text: '01. OSI и TCP/IP', link: '/network/01-osi-tcpip' },
            { text: '02. L2: Ethernet, MAC, ARP, VLAN', link: '/network/02-l2-ethernet-arp' },
            { text: '03. L3: IP, маршрутизация, ICMP', link: '/network/03-l3-ip-icmp' },
            { text: '04. L4: TCP и UDP', link: '/network/04-l4-tcp-udp' },
            { text: '05. DNS', link: '/network/05-dns' },
            { text: '06. HTTP', link: '/network/06-http' },
            { text: '07. TLS/SSL', link: '/network/07-tls' },
            { text: '08. SSH', link: '/network/08-ssh' },
            { text: '09. Утилиты диагностики', link: '/network/09-net-tools' },
            { text: '10. tcpdump и Wireshark', link: '/network/10-tcpdump-wireshark' },
            { text: '11. Файрвол: iptables/nftables', link: '/network/11-firewall-iptables' },
            { text: '12. Nginx', link: '/network/12-nginx' },
            { text: '13. HAProxy и балансировка', link: '/network/13-haproxy-balancing' },
            { text: '14. Путь запроса в браузере', link: '/network/14-url-journey' },
            { text: '15. Практика: лабы по сети', link: '/network/15-practice-labs' },
            { text: '16. Вопросы с собеседований', link: '/network/16-interview' },
            { text: '17. VPN', link: '/network/17-vpn' },
            { text: '18. Современные прокси', link: '/network/18-modern-proxies' },
          ],
        },
      ],
      '/linux/': [
        {
          text: 'Linux',
          items: [
            { text: 'Обзор темы', link: '/linux/' },
            { text: '00. Стенд: Vagrant + libvirt/KVM', link: '/linux/00-vagrant' },
            { text: '01. История, ядро, дистрибутивы', link: '/linux/01-getting-started' },
            { text: '02. Command Line', link: '/linux/02-command-line' },
            { text: '03. Text-Fu', link: '/linux/03-text-fu' },
            { text: '04. Advanced Text-Fu', link: '/linux/04-advanced-text-fu' },
            { text: '05. User Management', link: '/linux/05-user-management' },
            { text: '06. Permissions', link: '/linux/06-permissions' },
            { text: '07. Processes', link: '/linux/07-processes' },
            { text: '08. Packages', link: '/linux/08-packages' },
            { text: '09. Devices', link: '/linux/09-devices' },
            { text: '10. Файловая система', link: '/linux/10-the-filesystem' },
            { text: '11. Загрузка системы', link: '/linux/11-boot-the-system' },
            { text: '12. Ядро Linux', link: '/linux/12-kernel' },
            { text: '13. Init: systemd', link: '/linux/13-init' },
            { text: '14. Мониторинг процессов и cron', link: '/linux/14-process-utilization' },
            { text: '15. Логирование', link: '/linux/15-logging' },
            { text: '16. Network Sharing', link: '/linux/16-network-sharing' },
            { text: '17. Основы сетей', link: '/linux/17-network-basics' },
            { text: '18. Subnetting', link: '/linux/18-subnetting' },
            { text: '19. Маршрутизация', link: '/linux/19-routing' },
            { text: '20. Network Config', link: '/linux/20-network-config' },
            { text: '21. Troubleshooting', link: '/linux/21-troubleshooting' },
            { text: '22. DNS', link: '/linux/22-dns' },
            { text: '23. Bash Scripting: основы', link: '/linux/23-bash-basics' },
            { text: '24. Bash: условия, циклы, функции, массивы', link: '/linux/24-bash-control-flow' },
            { text: '25. Надёжный bash-скрипт', link: '/linux/25-bash-robust' },
            { text: '26. Bash в DevOps: боевые паттерны', link: '/linux/26-bash-devops-practice' },
            { text: '27. Практика: лабы', link: '/linux/27-practice-labs' },
            { text: '28. Вопросы с собеседований', link: '/linux/28-interview' },
          ],
        },
      ],
      '/git/': [
        {
          text: 'Git',
          items: [
            { text: 'Обзор темы', link: '/git/' },
            { text: '01. Что такое Git', link: '/git/01-git-intro' },
            { text: '02. Три области и команды init/add/commit', link: '/git/02-basics-workflow' },
            { text: '03. Удалённые репозитории', link: '/git/03-remote-repos' },
            { text: '04. Ветки и слияние', link: '/git/04-branches' },
            { text: '05. Merge conflict', link: '/git/05-merge-conflicts' },
            { text: '06. Rebase и cherry-pick', link: '/git/06-rebase-cherry-pick' },
            { text: '07. Отмена изменений и история', link: '/git/07-undo-history' },
            { text: '08. Теги и версионирование', link: '/git/08-tags-versioning' },
            { text: '09. Стратегии ветвления', link: '/git/09-branching-strategies' },
            { text: '10. Markdown', link: '/git/10-markdown' },
            { text: '11. Командная работа', link: '/git/11-collaboration' },
            { text: '12. Git в работе DevOps', link: '/git/12-git-in-devops' },
            { text: '13. Практика: лабы', link: '/git/13-practice-labs' },
            { text: '14. Вопросы с собеседований', link: '/git/14-interview' },
          ],
        },
      ],
    },

    search: {
      provider: 'local',
    },

    outline: [2, 3],

    outlineTitle: 'На этой странице',
    docFooter: {
      prev: 'Назад',
      next: 'Далее',
    },
    returnToTopLabel: 'Наверх',
    sidebarMenuLabel: 'Меню',
    darkModeSwitchLabel: 'Тема',
    lightModeSwitchTitle: 'Светлая тема',
    darkModeSwitchTitle: 'Тёмная тема',
  },
})
